import { Splits } from '@/types/Splits'

/**
 * Body del subscribe /topic/mensajes/asesor/datos/${accessToken}
 */
export interface AgentData {
	idUsuario: string
	idUsuarioBd: string
	email: string
	fullName: string
	idOrganizacion: number
	listadoClientes: Client[]
	activo: boolean
	schema: string
	clienteAsignado: boolean
	tiempoCliente: number
	tiempoAsesor: number
	tiempoInicioConversacion: number
	listadoSplit: Splits[]
	conexionAsesor: ConexionAsesor
	noValido: boolean
}

export interface AbstractClient {
	conversationId: number
	conversationStatus: ChatStatus
	conversacionAgenteHumano: ConversacionAsesorHumano
	nombre: string
	email: string
	identificacion: string
	tipoIdentificacion: string
	telefono: string
	ciudad: string
	departamento: string
	typeAlert: TypeAlert
	split: Splits
	channel: number
	idVa: number
	fromDirectory?: boolean
}

export interface Client extends AbstractClient {
	listadoMensajesVirtual: InteractionFact[]
	listadoMensajes: Mensaje[]
	schema: string
	requestData: string | null
	idOrganizacion: number
	escalado: boolean
	chatsEscalados: ChatsEscalados
}

export interface HistorialMensajes {
	listadoMensajes: InteractionFact[]
	error: string
}

export interface ClientState extends AbstractClient {
	active: boolean
	recover: boolean
	currentChatTime: string
	lastInteraction: string
	lastMessage: string
	messages: FormatedChat[]
	status: ChatStatus
	unreadMessages: number
	uploadFile: UploadFile
	causalsChecked: 'idle' | 'checking' | 'checked'
	escalado: boolean
	transferCompleted: 'idle' | 'true' | 'false'
	endCausals: boolean
	businessCausals: boolean
	causalsSetted: boolean
	transfer: boolean
	transfering: boolean
	sendingMessage: boolean
}

export interface UploadFile {
	error: boolean
	loading: boolean
}

/**
 * Interacciones entre cliente-asesor
 */
export interface Mensaje {
	tipoMensaje: TipoMensaje
	mensaje: string
	adjunto: Adjunto
	fechaMensaje: string
	conversationId: string
	asesorId: string
	almacenado: boolean
	tipoUsuario: TipoUsuario
}

export type TipoMensaje = 'CHAT' | 'JOIN' | 'LEAVE' | 'COMMAND'

export interface Adjunto {
	name: string
	url: string
	contentType: string
	blobUrl?: string
}

export type TipoUsuario = 'ASESOR' | 'CLIENTE' | 'SISTEMA'

/**
 * Interacciones entre cliente-bot
 */
export interface InteractionFact {
	id: number
	idRating: number
	interactionTime: string
	requestData: string
	responseAnswer: string
	conversationId: string
	idPrimaryIntent: number
	idSpecificIntent: number
	idInterDate: number
	idAdviser: number
}

export interface TypeAlert {
	category: string
	message: string
	title: string
	tooltip: string
}

export interface ConexionAsesor {
	idLogConexion: number
	idAsesor: number
	fechaConexion: string
	fechaDesconexion: string
	estado: string
	nombreAsesor: string
	logEventoPausa: LogEventoPausa
}

export interface LogEventoPausa {
	id: string | null
	idLogConnectionAgentHuman: number | null
	idPauseEvent: number | null
	pauseEventName: string | null
	startTime: string | null
	endTime: string | null
}

export interface RespuestaEventoPausa {
	logEventoPausa?: LogEventoPausa
	mensajeActivado?: string
	error?: string
}

export interface ConversacionAsesorHumano {
	idRegistro: number
	idConv: number
	idSplit: number
	idAsesor: number
	tipoFinConversacion: number
	atendido: boolean
	fechaEntradaConv: string
	fechaAsignacionConv: string
	fechaFinConv: string
	escalado: boolean
}

export interface ChatsEscalados {
	idRegistro: number
	idConv: number
	idSplitAnterior: number
	idSplitNuevo: number
	idAsesorAnterior: number
	idAsesorNuevo: number
	fechaEscalado: string
	fechaAsignado: string
}

export interface Message {
	id: number
	agentMssg: string
	agentFile: File
	agentDatetimeMssg: string
	clientMssg: string
	clientFile: File
	clientDatetimeMssg: string
}

export type AgentStatus = 'CONECTADO' | 'DESCONECTADO' | 'PAUSA'

export type ChatStatus = 'ACTIVO' | 'FINALIZADO' | 'ENTRANTE'

export interface FormatedChat {
	id: string
	itemType: number
	itemOptions: string[]
	messageTime: string
	message: string
	file: Adjunto | null
	client: boolean
	interactionId?: number
}

// Generated by https://quicktype.io

export interface RequestData {
	channel: number
	context: Context
	metadata: Metadata
	negacion: string
	// nodeId:          any[];
	nodeLabel: string
	number: number
	primaryIntent: string
	rating: boolean
	split: number
	timezone: string
	whatsappContact: WhatsappContact
	idAgent: number
	organization: number
	text: string
}

export interface Context {
	CityCodeWpp: string
	CityNameWpp: string
	CityUndefined: boolean
	EmailWpp: string
	IdNumberWpp: string
	Idchannel: number
	InfoFormWppCompleted: boolean
	NameClientWpp: string
	NumberPhoneWpp: string
	PhoneNumberWpp: string
	Solicitudes: string
	TypeIdNumberWpp: string
	confirmacion: string
	counter_to_transfer: number
	descripcion: string
	endCustIdCity: string
	endCustIdNumber: string
	endCustIdType: string
	endCustMail: string
	endCustName: string
	endCustPhone: string
	fileArrayAttachment: FileArrayAttachment[]
	initial_message_wpp: string
	intencion: string
}

export interface FileArrayAttachment {
	itemType: number
	itemFile?: ItemFile
	itemValue: string
	name?: string
	contentType?: string
	url?: string
}

export interface ItemFile {
	name: string
	contentType: string
	url: string
}

export interface Metadata {
	user_id: string
}

export interface WhatsappContact {
	displayName: string
	phone: string
}

export interface ResponseAnswer {
	responseItems: ResponseItems[]
}

export interface ResponseItems {
	itemType: number
	itemValue?: string
	itemOptions?: string[]
	itemFile?: Adjunto | null
}

export interface PlainMessageReceived {
	adjunto: Adjunto | null
	content: string
	conversationId: string
	error: string
	idSplit: number | null
	interactionId: string
	tipoMensaje: TipoMensaje
	tipoUsuario: TipoUsuario
}

export interface PlainMessageSend {
	adjunto: Adjunto | null
	asesorId: string
	mensaje: string
	tipoUsuario: TipoUsuario
	tipoMensaje: TipoMensaje
	fechaMensaje?: string
	conversationId?: number | string
	idSplitDestino?: number
}

export interface RecuperarHistorialPublish {
	tipoUsuario: TipoUsuario
	idAsesor: string | null
}

export interface UpdateChatPayload {
	conversationId: number
	message: FormatedChat
}

export interface MessagesHistoryPayload {
	conversationId: number
	lastMessage: string
	lastInteraction: string
	messages: FormatedChat[]
}

export type EndConversationCommand =
	| 'FCTIC'
	| 'FCTIA'
	| 'FCTIAI'
	| 'FCCC'
	| 'FCCA'
	| 'FCE'
	| 'FCFHL'
	| AgentDisconnectionCommand

export type StartConversationCommand = 'IC'
export type TransferCommand = 'TCOS' | 'TCOSOK' | 'TCOSERROR'
export type AgentDisconnectionCommand = 'CCCNE'
export type AgentDisconnectionWithChatsCommand = 'DACA'
export type AgentManualDisconnectionCommand = 'DAM'

export type GeneralCommand =
	| 'NDF'
	| 'NAPA'
	| 'FHSONR'
	| 'SASONR'
	| 'NPASD'
	| 'NAC'
	| 'ECANPR'
	| 'ECCNPR'
	| 'Cliente en cola'
	| ''

export type Command = EndConversationCommand &
	StartConversationCommand &
	TransferCommand &
	AgentDisconnectionCommand &
	GeneralCommand

export interface PublishMessage {
	message: string
	conversationId: number
	file: Adjunto | null
	tipoMensaje?: TipoMensaje
	idSplitDestino?: number
}

export interface LogSocket {
	idOrg: number
	payload: {
		application?: string
		callback: string
		detail: string
		idadviser: number
	}
}

export interface LogSocketFromCausals {
	idOrg: number
	idadviser: number
}
